######################## default configuration ####################
baseURL = "https://debate-sdul.github.io"
title = "SDUL"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "5"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-DFBQ2VGYZB" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true